server:
  port: 1313

spring:
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        current_session_context_class:  org.springframework.orm.hibernate5.SpringSessionContext
#        temp:
#          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  security:
    user:
      name: admin
      password: admin